print ("Hello World")
print ("Aswin")
print (10+10)
# print("Aswin", sep=" ", end=" ")
print("Kumar")
print("Adwith", sep=" ", end=" ")
print("Aswin", sep=" ", end=" & ")
print("Aswin", sep=" ", end=" ")
print("Kumar")
print(100+100)
print(2/2)